# Generated by Django 4.2.25 on 2025-10-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='posted_date',
            field=models.DateField(),
        ),
    ]
