# Generated by Django 5.2.7 on 2025-10-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('edition', models.CharField(max_length=50)),
                ('pages', models.IntegerField()),
                ('published_date', models.DateField()),
            ],
        ),
    ]
